variables:
  azureSubscription: 'AZR-RWD-PRD1'    
  docker.imageName: 'eprcalculatorfssapi'      
  acr.azureContainerRegistryName: 'prdrwdinfac1401'
  acr.repositoryName: 'eprcalculatorfssapirepository'   
  serviceName: 'prdrwdwebwa1426'   
